parserOptions:
  ecmaVersion: 2017
env:
  browser: true
  es6: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-template-curly-in-string:
    - error
  valid-jsdoc:
    - error
  eqeqeq:
    - error
  dot-notation:
    - error
  comma-dangle:
    - error
    - only-multiline

